services:
  postgres:
    image: postgres:18
    container_name: ecommerce-postgres
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ecommerce-postgres-data:/var/lib/postgresql

volumes:
  ecommerce-postgres-data: